// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Copyright (c) 2026 Nayeem Bin Ahsan
use log::info;

use super::book_init::{BookInit, PickerInit};

pub(super) fn build_loop_state(
    book: BookInit,
    picker: PickerInit,
    body_px: f32,
    head_px: f32,
    line_h: i32,
    line_spacing_pct: i32,
    text_justify: bool,
    w: usize,
    h: usize,
    device_model: &'static str,
    wifi_user_on: bool,
    bt_user_on: bool,
) -> crate::loop_state::LoopState {
    let cached = crate::panel::load_voice_cache();
    if !cached.is_empty() {
        let count = cached.len();
        crate::panel::set_dynamic_voices(cached);
        info!("loaded {count} cached voices");
    }
    // Adopt the buffers the launch paint already filled rather than allocating
    // fresh ones: in the library that paint *is* the screen, and `text_cache`
    // is what a panel close restores from.
    let buffer = picker.buffer;
    let prev_buffer = buffer.clone();
    let text_cache = picker.text_cache;
    debug_assert_eq!(buffer.len(), w * h, "launch buffer must match the panel");
    let now = std::time::Instant::now();
    crate::loop_state::LoopState {
        current_chapter: book.4,
        current_page: book.6,
        chapter_count: book.1,
        chapters: book.0,
        toc_rows: book.17,
        chapter_offsets: book.2,
        state: book.5,
        body_px,
        head_px,
        line_h,
        line_spacing_pct,
        text_justify,
        current_book_path: book.11,
        reading_ch: book.7,
        reading_pg: book.8,
        reading_off: book.9,
        reading_end: book.10,
        picker_active: picker.active,
        picker_scroll: picker.scroll,
        picker_cells: picker.cells,
        library_filter: crate::rendering::render::LibraryFilter::default(),
        picker_cover_cache: picker.cover_cache,
        picker_entered: picker.entered,
        panel_open: false,
        prev_panel_open: false,
        prev_chapter_overlay: false,
        cover_page_visible: book.12,
        chapter_scroll: 0,
        press_chapter_scroll: 0,
        word_index: book.18,
        chapter_tab: Default::default(),
        search_scroll: 0,
        search_results_active: false,
        search_results_scroll: 0,
        search_selected_word: 0,
        search_word_selected: false,
        search_selected_result: 0,
        search_result_selected: false,
        press_search_scroll: 0,
        press_search_results_scroll: 0,
        sb_dragging: false,
        sb_drag_tab: Default::default(),
        sb_grab_offset: 0,
        bt_fail_count: 0,
        text_dirty: book.13,
        #[cfg(feature = "screenshot")]
        shot_armed: false,
        #[cfg(feature = "screenshot")]
        shot_done: false,
        system_state: crate::SystemState::Awake,
        view_mode: book.14,
        prev_view_mode: book.14,
        bookmark: book.15,
        lock_time: None,
        saved_brightness: 0,
        lock_radios_off: false,
        lock_wifi_off: false,
        lock_bt_off: false,
        wifi_user_on,
        bt_user_on,
        disk_key: None,
        disk_cover: None,
        disk_cover_path: String::new(),
        cover_rotation: 0.0,
        prev_cover_rotation: 0.0,
        last_cover_rot: now,
        disk_spin_only: false,
        disk_settle: false,
        prev_playing: false,
        prev_down: false,
        frame_down: false,
        frame_x: 0,
        frame_y: 0,
        tap_xy: None,
        scrubbing: false,
        pp_pressed: false,
        pp_pending_release: None,
        saved_pos: None,
        saved_pos_at: None,
        lib_pressed: false,
        menu_pressed: false,
        mode_toggle_pressed: false,
        bookmark_set_pressed: false,
        bookmark_jump_pressed: false,
        sleep_pressed: false,
        chapter_pressed: false,
        header_visible: true,
        header_revealed_at: None,
        pending_tap_at: None,
        press_dispatched: false,
        press_x: 0,
        press_y: 0,
        press_time: now,
        last_double_tap: now,
        last_tap_time: now,
        last_tap_y: -1,
        picker_last_tap_idx: None,
        picker_last_tap_time: now,
        exit_armed: false,
        about_open: false,
        device_model: device_model.to_string(),
        exit_armed_time: now,
        offset_rx: book.3,
        last_activity: now,
        last_status_refresh: now,
        last_nav: now,
        last_font_count: 0,
        buffer,
        prev_buffer,
        text_cache,
        zoom_active: false,
        zoom_center: (0, 0),
        voice_rx: None,
        voice_fetch_attempted: false,
        wifi_bt_list_rx: None,
        font_download_rx: None,
        update_check_rx: None,
        wifi_list: Vec::new(),
        wifi_list_idx: 0,
        wifi_list_fetched: false,
        wifi_list_ids_valid: true,
        bt_list: Vec::new(),
        bt_list_idx: 0,
        bt_list_fetched: false,
        bt_list_ids_valid: true,
    }
}
